{
 "title": "WAN Exporter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wan_bandwidth_bps", "legendFormat": " {{ dir }}" }
   ]
  },
  {
   "title": "Available bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "expr": "wan_bandwidth_bps", "legendFormat": "{{ dir }}" }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "wan_latency_seconds", "legendFormat": "{{ server }}" }
   ]
  },
  {
   "title": "Measured latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "wan_latency_seconds", "legendFormat": "{{ server }}" }
   ]
  },
  {
   "title": "Latency histogram",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(wan_latency_hist_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}